[tools]
jq = "latest"
node = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
zoxide = "latest"
imagemagick = "latest"
ffmpeg = "latest"
yazi = "latest"
duf = "latest"
bat = "latest"
eza = "latest"
lazygit = "latest"
tmux = "latest"
yt-dlp = "latest"
